yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

handler404 = 'core.views.page_not_found'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()

POST_PREVIEW = 15


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название группы')
    slug = models.SlugField(
        unique=True,
        verbose_name='Человекочитаемый URL группы'
    )
    description = models.TextField(verbose_name='Описание группы')

    def __str__(self) -> str:
        return f'{self.title}'


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст записи',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Название группы',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self) -> str:
        return f'{self.text[:POST_PREVIEW]}'

    class Meta:
        ordering = ['-pub_date']


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментируемый пост',
        help_text='Пост, к которому будет относиться комментарий'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария',
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата и время комментария'
    )

    def __str__(self) -> str:
        return f'{self.text[:POST_PREVIEW]}'

    class Meta:
        ordering = ['-created']


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Подписчик',
    )

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        help_texts = {
            'group': ('Выберите группу (необязательно)'),
            'text': ('Введите текст поста'),
            'image': ('Добавить изображение (необязательно)')
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        help_texts = {
            'text': ('Оставьте комментарий...')
        }

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models.functions import Length
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import PostForm, CommentForm
from .models import Follow, Group, Post

User = get_user_model()

POSTS_PER_PAGE = 10


def pagination(request, posts):
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


@cache_page(20)
def index(request):
    posts = (
        Post.objects.all().
        select_related('author', 'group').
        annotate(post_length=Length('text'))
    )
    page_obj = pagination(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = (
        group.posts.select_related('author').
        annotate(post_length=Length('text'))
    )
    page_obj = pagination(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author=author)
    follower = Follow.objects.filter(
        user=request.user,
        author=author
    )
    following = False
    if request.user.is_authenticated and follower.exists():
        following = True
    page_obj = pagination(request, posts)
    context = {
        'author': author,
        'following': following,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(
        Post.objects.
        select_related('author', 'group'),
        id=post_id
    )
    form = CommentForm()
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    context = {}
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if request.method == 'POST':
        context['form'] = form
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', username=request.user)
        context['errors'] = form.errors
        return render(request, 'posts/create_post.html', context)
    context['form'] = form
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = Post.objects.get(id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    return render(
        request,
        'posts/create_post.html',
        {'form': form, 'is_edit': True}
    )


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(
        author__following__user=request.user
    )
    page_obj = pagination(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=author)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follower = Follow.objects.filter(
        user=request.user,
        author=author
    )
    if follower.exists():
        follower.delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
  <title>
    {% if is_edit %}
      Редактировать записи
    {% else %}
      Создать новую запись
    {% endif %}
  </title>
{% endblock title %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактирование записи
            {% else %}
              Новая запись
            {% endif %}
          </div>
          <div class="card-body">
            {% load user_filters %}
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
            <form method="post" enctype="multipart/form-data"
            action="
            {% if is_edit %}
              {% url 'posts:post_edit' form.instance.id %}
            {% else %}
              {% url 'posts:post_create' %}
            {% endif %}
            ">
                {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                    {% if field.field.required %}
                    <span class="required text-danger">*</span>
                    {% endif %}
                </label>
                {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small
                      id="{{ field.id_for_label }}-help"
                      class="form-text text-muted"
                    >
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
              </div>
            {% endfor %}
              <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
              </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div> <!-- container -->
{% endblock content %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %} <title> Последние обновления избранных авторов </title> {% endblock title %}
{% block content %}
  <div class="container py-5">
    <h1> Последние обновления избранных авторов </h1>
    {% include 'includes/switcher.html' %}
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author %}">
              (все посты пользователя)
            </a>
          </li>
          {% if post.group %}
          <li>
            Группа: {{ post.group }}
          </li>
          {% endif %}
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p>
        <a href="{% url 'posts:post_detail' post.id %}">
          Подробная информация
        </a>
        {% if post.group %}
        <p>
          <a href="{% url 'posts:group_list' post.group.slug %}">
          Все записи группы "{{ post.group }}"
          </a>
        </p>
        {% endif %}
      </article>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
  {% include 'includes/paginator.html' %}
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} <title> Записи сообщества {{ group.title }} </title> {% endblock title %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author %}">
              (все посты пользователя)
            </a>
          </li>
          {% if post.group %}
          <li>
            Группа: {{ post.group.title }}
          </li>
          {% endif %}
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p>
        <a href="{% url 'posts:post_detail' post.id %}">
          Подробная информация
        </a>
      </article>
        <p><a href="{% url 'posts:index' %}">Вернуться на главную</a></p>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
  {% include 'includes/paginator.html' %}
{% endblock content %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %} <title> Последние обновления на сайте </title> {% endblock title %}
{% block content %}
  <div class="container py-5">
    <h1> Последние обновления на сайте </h1>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author %}">
              (все посты пользователя)
            </a>
          </li>
          {% if post.group %}
          <li>
            Группа: {{ post.group }}
          </li>
          {% endif %}
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
        <a href="{% url 'posts:post_detail' post.id %}">
          Подробная информация
        </a>
        {% if post.group %}
        <p>
          <a href="{% url 'posts:group_list' post.group.slug %}">
          Все записи группы "{{ post.group }}"
          </a>
        </p>
        {% endif %}
      </article>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
  {% include 'includes/paginator.html' %}
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %} <title>Пост {{ post.text|truncatechars:30 }}</title> {% endblock title %}
{% block content %}
<div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
        <li class="list-group-item">
          Группа: {{ post.group }}
          <a href="{% url 'posts:group_list' post.group.slug %}">
            Все записи группы
          </a>
        </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span> {{ post.author.posts.count }} </span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            Все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
      {{ post.text }}
      </p>
      {% if post.author.username == user.username %}
      <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">Редактировать</a>
      {% endif %}
      {% include 'includes/comments.html' %}
    </article>
  </div>
</div>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %} <title> Профайл пользователя {{ author.get_full_name }} </title> {% endblock title %}
{% block content %}
  <div class="container py-5">
    <div class="mb-5">
      <h1>Все посты пользователя {{ author.get_full_name }} </h1>
      <h3>Всего постов: {{ author.posts.count }} </h3>
      {% if request.user != author %}
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
              Подписаться
            </a>
        {% endif %}
      {% endif %}
    </div> <!--mb-5-->
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p>
        <a href="{% url 'posts:post_detail' post.id %}">Подробная информация </a>
        {% if post.group %}
        <p>
          <a href="{% url 'posts:group_list' post.group.slug %}">
            Все записи группы "{{ post.group }}"
          </a>
        </p>
        {% endif %}
      </article>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div> <!--container py-5-->
  {% include 'includes/paginator.html' %}
{% endblock content %}